replace firefox profile dir nssdb with global one
by symlinking, this allows only trusted certs to be used
and none of the hardcoded ones

diff --git a/bin.prepend/fox b/bin.prepend/fox
--- a/bin.prepend/fox
+++ b/bin.prepend/fox
@@ -133,10 +133,12 @@ prefix=(
 
   --setenv "LANG" "${LANG:=en_US.utf8}" #the := also sets LANG if it's unset or null, as opposed to :- which doesn't.
 
+  #XXX: this was likely due to permission error where only root had read perms on /etc/pki/nssdb/ files!
+  #this alone has no effect:--setenv "NSS_DEFAULT_DB_TYPE" "sql:/etc/pki/nssdb"
   #--setenv "NSS_DEFAULT_DB_TYPE" "sql:/etc/pki/nssdb" #no effect:tell firefox to use the global cert database instead of a local one that it re-makes if doesn't exist, in each ff profile dir. that /etc/pki/nssdb/ dir gets regenerated after each emerge of dev-libs/nss via /etc/portage/env/dev-libs/nss
-  #--setenv "NSS_DEFAULT_DB_TYPE" "sql"
+  #--setenv "NSS_DEFAULT_DB_TYPE" "sql" #i dno if it has any effect, tried it
   #in about:config the security.enterprise_roots.enabled preference to set its value to true. This enables Firefox to use the global NSS database (nssdb) specified by the environment variable MOZ_NSS_DIR or by default paths recognized by Firefox.
-  #--setenv "MOZ_NSS_DIR" "/etc/pki/nssdb" #no effect!
+  #--setenv "MOZ_NSS_DIR" "/etc/pki/nssdb" #no effect! even now that nssdb has read perms!
 
   --ro-bind /etc /etc
 
@@ -313,6 +315,14 @@ getprofilesfullpathdirs_aftermanglefor_foxelem() {
         #if here, they're different
         cp -a -v -f -T -- "/swcode/data/user.js" "${firstarg}/user.js" >/dev/null || exit 88
       fi
+
+      #XXX: only this variant works! all other tries seems to see only the trusted hardcoded certs! like this: https://wiki.gentoo.org/wiki/Certificates#NSS-based_modifications
+      rm -v -- "${firstarg}"/{cert9.db,key4.db,pkcs11.txt} 1>&2
+      set -e
+      #works, but if it doesn't have permission to read them, it still somehow ends up using the hardcoded certs! oddly enough! it's that /usr/lib64/libnssckbi.so file which somehow manages that even without re-creating the nssdb in profile dir (since it can't, due to no perm to rewrite them)
+      ln -vrs "--target-directory=${firstarg}" -- /etc/pki/nssdb/{cert9.db,key4.db,pkcs11.txt} 1>&2
+      #cp -a "--target-directory=${firstarg}" -- /etc/pki/nssdb/{cert9.db,key4.db,pkcs11.txt} >/dev/null
+      set +e
 
       #TODO: test so the args don't have spaces and other bad stuff here
       echo "--bind ${firstarg} ${secondarg}"; #secondarg is what's seen inside bwrap!
